### ISSUE TITLE
v.7.0 build asset missing

### ISSUE THREAD

**Issue by listelin** [MMD-Blender/blender_mmd_tools_append#35]
v.7.0リリースありがとうございます

しかしソースコードのみでビルドされたzipがありません

Thank you for the v.7.0 release!

But there is no built zip, only source code

**Comment by UuuNyaa** [comment]
リリース手順を間違えました。
もう一度v0.7.0をリリースしたので、確認をお願いします。

I made a mistake in the release steps.
I have released v0.7.0 again, please check it.

**Comment by listelin** [comment]
ありがとうございました。
正常にインストールでき、動作も問題なさそうです
